spring:
  application:
    name: Sample Lombok
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:lombok
    driverClassName: org.h2.Driver
    username: test
    password: test
    
server:
  port: 9080